---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: web
      labels:
        app: the_answer
        component: web
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: the_answer
          component: web
      template:
        metadata:
          name: web
          labels:
            app: the_answer
            component: web
        spec:
          containers:
          - image: alexpotapov87/web_ta:latest
            name: web
            imagePullPolicy: Always