apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
    labels:
        app: the_answer
        network: nginx_internal
        component: nginx
spec:
    replicas: 2
    selector:
        matchLabels:
            app: the_answer
            network: nginx_internal
            component: nginx    
    template:
        metadata:
            name: nginx
            labels:
                app: the_answer
                network: nginx_internal
                component: nginx    
        spec:
            terminationGracePeriodSeconds: 10
            containers:
            - name: nginx              
              image: alexpotapov87/ta_nginx:latest
              imagePullPolicy: "Always"
            - name: nginx-exporter
              image: nginx/nginx-prometheus-exporter
              args:
                - '-nginx.scrape-uri=http://localhost:8081/stub_status'