apiVersion: apps/v1
kind: Deployment
metadata:
    name: prometheus
    labels:
        app: the_answer
        network: nginx_internal
        component: prometheus
spec:
    replicas: 1
    selector:
        matchLabels:
            app: the_answer
            network: nginx_internal
            component: prometheus    
    template:
        metadata:
            name: prometheus
            labels:
                app: the_answer
                network: nginx_internal
                component: prometheus    
        spec:
            terminationGracePeriodSeconds: 10
            containers:
            - image: alexpotapov87/ta_prom:latest
              name: prometheus
              imagePullPolicy: "Always"
              volumeMounts:
              - mountPath: "/prometheus"
                name: prometheus-pv-storage
            volumes:
            - name: prometheus-pv-storage
              persistentVolumeClaim:
                claimName: prometheus-pv-claim
