apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  labels:
    app: the_answer
    component: cadvisor
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: the_answer
    component: cadvisor
