apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: the_answer
    network: nginx_internal
    component: nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: the_answer
    network: nginx_internal
    component: nginx
