apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: the_answer
    network: nginx_internal
    component: nginx
spec:
  ports:
  - name: nginx
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: nginx-metrics
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: exporter
    port: 9113
    protocol: TCP
    targetPort: 9113
  selector:
    app: the_answer
    network: nginx_internal
    component: nginx
