apiVersion: v1
kind: Service
metadata:
  labels:
    app: the_answer
    component: node-exporter
  name: node-exporter
spec:
  ports:
  - name: '9100'
    port: 9100
    targetPort: 9100
  selector:
    app: the_answer
    component: node-exporter
