apiVersion: v1
kind: Service
metadata:
  labels:
    app: the_answer
    component: node-exporter
  name: node-exporter
spec:
  clusterIP: None
  ports:
  - name: https
    port: 9100
    targetPort: https
  selector:
    app: the_answer
    component: node-exporter
