apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  labels:
    network: nginx_internal
    component: nginx-exporter
spec:
  ports:
  - port: 9113
    protocol: TCP
    targetPort: 9113
  selector:
    network: nginx_internal
    component: nginx-exporter
