apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: the_answer
    component: web
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: the_answer
    component: web
